[package]
name = "minicode"
version = "0.1.2"
edition = "2021"

[dependencies]
clap = { version = "4.4.13", features = ["derive"] }
self_update = { version = "0.39.0", features = ["archive-tar", "archive-zip", "compression-flate2"] }
